import Darwin
import Foundation
import XCTest
@testable import FreshProfile

final class SessionPresentationTests: XCTestCase {
    func testNormalizesSessionName() {
        XCTAssertEqual(
            SessionName.normalized("  Client   research  ", fallbackNumber: 1),
            "Client research"
        )
        XCTAssertEqual(
            SessionName.normalized("   ", fallbackNumber: 7),
            "Profile 7"
        )
        XCTAssertEqual(
            SessionName.normalized(
                String(repeating: "a", count: 80),
                fallbackNumber: 1
            ).count,
            SessionName.maximumLength
        )
    }

    func testLandingPageEscapesNameAndUsesColor() {
        let metadata = SessionMetadata(
            name: "<Work & \"Mail\">",
            color: .rose,
            createdAt: Date(timeIntervalSince1970: 0)
        )
        let html = SessionLandingPage.html(metadata: metadata)

        XCTAssertTrue(html.contains("&lt;Work &amp; &quot;Mail&quot;&gt;"))
        XCTAssertFalse(html.contains("<Work &"))
        XCTAssertTrue(html.contains(SessionColor.rose.hex))
    }

    func testLandingPageDescribesSavedProfile() {
        let metadata = SessionMetadata(
            name: "Research",
            color: .violet,
            createdAt: Date(timeIntervalSince1970: 0),
            isPersistent: true
        )
        let html = SessionLandingPage.html(metadata: metadata)

        XCTAssertTrue(html.contains("Saved profile"))
        XCTAssertTrue(
            html.contains("cookies and logins remain available")
        )
    }

    func testChromeArgumentsUseIsolatedProfileAndLandingPage() {
        let profileURL = URL(fileURLWithPath: "/tmp/Fresh Profile")
        let landingURL = profileURL.appendingPathComponent("Start.html")
        let arguments = SessionLauncher.arguments(
            profileURL: profileURL,
            landingPageURL: landingURL,
            color: .rose
        )

        XCTAssertTrue(
            arguments.contains("--user-data-dir=\(profileURL.path)")
        )
        XCTAssertFalse(arguments.contains("--incognito"))
        XCTAssertTrue(arguments.contains("--new-window"))
        XCTAssertTrue(
            arguments.contains("--install-autogenerated-theme=230,107,145")
        )
        XCTAssertTrue(arguments.contains("--remote-debugging-pipe"))
        XCTAssertEqual(arguments.last, landingURL.absoluteString)
    }

    func testChromeProcessUsesPrivateDevToolsPipeDescriptors() {
        let browserURL = URL(
            fileURLWithPath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        )
        let profileURL = URL(fileURLWithPath: "/tmp/Fresh Profile")
        let landingURL = profileURL.appendingPathComponent("Start.html")
        let arguments = SessionLauncher.processArguments(
            browserExecutableURL: browserURL,
            profileURL: profileURL,
            landingPageURL: landingURL,
            color: .rose
        )

        XCTAssertEqual(arguments[0], "-c")
        XCTAssertTrue(arguments[1].contains("3<&0 4>&1"))
        XCTAssertEqual(arguments[2], browserURL.path)
        XCTAssertTrue(arguments.contains("--remote-debugging-pipe"))
    }

    func testDockTileMessageContainsPNGAndNullTerminator() throws {
        let pngData = Data([0x89, 0x50, 0x4e, 0x47])
        let message = try DockTileProtocol.setIconMessage(pngData: pngData)

        XCTAssertEqual(message.last, 0)
        let object = try XCTUnwrap(
            JSONSerialization.jsonObject(
                with: Data(message.dropLast())
            )
                as? [String: Any]
        )
        XCTAssertEqual(object["method"] as? String, "Browser.setDockTile")
        let params = try XCTUnwrap(object["params"] as? [String: String])
        XCTAssertEqual(params["image"], pngData.base64EncodedString())
    }

    func testCreateWindowMessageUsesNewFocusedWindow() throws {
        let message = try DockTileProtocol.createWindowMessage(id: 7)
        let object = try XCTUnwrap(
            JSONSerialization.jsonObject(
                with: Data(message.dropLast())
            ) as? [String: Any]
        )

        XCTAssertEqual(object["id"] as? Int, 7)
        XCTAssertEqual(object["method"] as? String, "Target.createTarget")
        let params = try XCTUnwrap(object["params"] as? [String: Any])
        XCTAssertEqual(params["url"] as? String, "chrome://newtab/")
        XCTAssertEqual(params["newWindow"] as? Bool, true)
        XCTAssertEqual(params["focus"] as? Bool, true)
        XCTAssertEqual(message.last, 0)
    }

    func testFindsApplicationBundleForChromeExecutable() {
        let executableURL = URL(
            fileURLWithPath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        )

        XCTAssertEqual(
            SessionDockIcon.applicationBundleURL(for: executableURL)?.path,
            "/Applications/Google Chrome.app"
        )
        XCTAssertNil(
            SessionDockIcon.applicationBundleURL(
                for: URL(fileURLWithPath: "/usr/local/bin/chrome")
            )
        )
    }

    func testInstalledChromeAcceptsDockTileIcon() throws {
        guard ProcessInfo.processInfo.environment[
            "FRESH_PROFILE_DOCK_INTEGRATION"
        ] == "1" else {
            throw XCTSkip("Requires the opt-in macOS Chrome integration test.")
        }

        let browser = try XCTUnwrap(
            BrowserLocator().installedBrowsers().first
        )
        let temporaryRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = try ProfileStore(rootURL: temporaryRoot)
        let launcher = try SessionLauncher(profileStore: store)
        let launched = try launcher.launch(
            browser: browser,
            name: "Dock Test",
            color: .rose
        ) { _ in }

        defer {
            stopProcess(launched.process)
            try? FileManager.default.removeItem(at: temporaryRoot)
        }

        if let outputPath = ProcessInfo.processInfo.environment[
            "FRESH_PROFILE_DOCK_ICON_OUTPUT"
        ] {
            let pngData = try XCTUnwrap(
                SessionDockIcon.pngData(
                    browserExecutableURL: browser.executableURL,
                    color: .rose
                )
            )
            try pngData.write(to: URL(fileURLWithPath: outputPath))
        }

        let connection = try XCTUnwrap(launched.dockTileConnection)
        let response = try XCTUnwrap(connection.response(timeout: 10))
        XCTAssertEqual(response["id"] as? Int, 1)
        XCTAssertNotNil(response["result"])
        XCTAssertNil(response["error"])
    }

    func testInstalledChromeReopensPersistentProfile() throws {
        guard ProcessInfo.processInfo.environment[
            "FRESH_PROFILE_DOCK_INTEGRATION"
        ] == "1" else {
            throw XCTSkip("Requires the opt-in macOS Chrome integration test.")
        }

        let browser = try XCTUnwrap(
            BrowserLocator().installedBrowsers().first
        )
        let temporaryRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let store = try ProfileStore(rootURL: temporaryRoot)
        let launcher = try SessionLauncher(profileStore: store)
        let firstLaunch = try launcher.launch(
            browser: browser,
            name: "Saved Test",
            color: .mint,
            isPersistent: true
        ) { _ in }

        stopProcess(firstLaunch.process)

        let profileMarker = firstLaunch.profileURL
            .appendingPathComponent(".freshprofile")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: profileMarker.path)
        )
        let storedProfile = try XCTUnwrap(
            store.persistentProfiles().first
        )
        XCTAssertEqual(storedProfile.id, firstLaunch.id)

        let secondLaunch = try launcher.relaunch(
            browser: browser,
            storedProfile: storedProfile
        ) { _ in }

        defer {
            stopProcess(secondLaunch.process)
            try? FileManager.default.removeItem(at: temporaryRoot)
        }

        XCTAssertEqual(secondLaunch.id, firstLaunch.id)
        XCTAssertEqual(secondLaunch.profileURL, firstLaunch.profileURL)
        XCTAssertTrue(secondLaunch.process.isRunning)
        let connection = try XCTUnwrap(
            secondLaunch.dockTileConnection
        )
        XCTAssertNotNil(connection.response(timeout: 10))
        XCTAssertEqual(connection.ensureWindow(), .existing)
        XCTAssertTrue(
            connection.closePageTargetsForTesting(timeout: 10)
        )
        Thread.sleep(forTimeInterval: 0.3)
        XCTAssertEqual(connection.ensureWindow(timeout: 10), .created)
        XCTAssertTrue(secondLaunch.process.isRunning)
    }

    private func stopProcess(_ process: Process) {
        guard process.isRunning else { return }
        process.terminate()
        let deadline = Date().addingTimeInterval(5)
        while process.isRunning && Date() < deadline {
            Thread.sleep(forTimeInterval: 0.05)
        }
        if process.isRunning {
            kill(process.processIdentifier, SIGKILL)
        }
        process.waitUntilExit()
    }
}
