import Foundation

struct LaunchedSession {
    let id: UUID
    let process: Process
    let profileURL: URL
    let metadata: SessionMetadata
    let dockTileConnection: DockTileConnection?
}

struct SessionLauncher {
    let profileStore: ProfileStore

    init(profileStore: ProfileStore? = nil) throws {
        self.profileStore = try profileStore ?? ProfileStore()
    }

    func launch(
        browser: Browser,
        name: String,
        color: SessionColor,
        isPersistent: Bool = false,
        onTermination: @escaping (UUID) -> Void
    ) throws -> LaunchedSession {
        let id = UUID()
        let metadata = SessionMetadata(
            name: name,
            color: color,
            createdAt: Date(),
            isPersistent: isPersistent
        )
        let profileURL = try profileStore.createProfile(
            id: id,
            metadata: metadata
        )

        return try launchProfile(
            id: id,
            browser: browser,
            profileURL: profileURL,
            metadata: metadata,
            removeProfileOnFailure: true,
            onTermination: onTermination
        )
    }

    func relaunch(
        browser: Browser,
        storedProfile: StoredProfile,
        onTermination: @escaping (UUID) -> Void
    ) throws -> LaunchedSession {
        guard storedProfile.metadata.isPersistent else {
            throw SessionLauncherError.profileIsNotPersistent
        }
        guard !profileStore.isProfileInUse(storedProfile.profileURL) else {
            throw SessionLauncherError.profileAlreadyRunning
        }

        return try launchProfile(
            id: storedProfile.id,
            browser: browser,
            profileURL: storedProfile.profileURL,
            metadata: storedProfile.metadata,
            removeProfileOnFailure: false,
            onTermination: onTermination
        )
    }

    static func processArguments(
        browserExecutableURL: URL,
        profileURL: URL,
        landingPageURL: URL,
        color: SessionColor
    ) -> [String] {
        [
            "-c",
            "exec 3<&0 4>&1; exec \"$0\" \"$@\"",
            browserExecutableURL.path
        ] + arguments(
            profileURL: profileURL,
            landingPageURL: landingPageURL,
            color: color
        )
    }

    static func arguments(
        profileURL: URL,
        landingPageURL: URL,
        color: SessionColor
    ) -> [String] {
        [
            "--user-data-dir=\(profileURL.path)",
            "--new-window",
            "--no-first-run",
            "--no-default-browser-check",
            "--install-autogenerated-theme=\(color.chromeThemeRGB)",
            "--remote-debugging-pipe",
            landingPageURL.absoluteString
        ]
    }

    private func launchProfile(
        id: UUID,
        browser: Browser,
        profileURL: URL,
        metadata: SessionMetadata,
        removeProfileOnFailure: Bool,
        onTermination: @escaping (UUID) -> Void
    ) throws -> LaunchedSession {
        let landingPageURL = try SessionLandingPage.write(
            metadata: metadata,
            to: profileURL
        )
        let process = Process()
        let dockTileConnection = DockTileConnection(
            browserExecutableURL: browser.executableURL,
            color: metadata.color
        )

        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = Self.processArguments(
            browserExecutableURL: browser.executableURL,
            profileURL: profileURL,
            landingPageURL: landingPageURL,
            color: metadata.color
        )
        dockTileConnection?.configure(process)

        process.terminationHandler = { _ in
            if metadata.isPersistent {
                try? profileStore.clearProcessID(for: profileURL)
            } else {
                Self.removeProfileWithRetries(
                    profileURL,
                    profileStore: profileStore
                )
            }
            onTermination(id)
        }

        do {
            try process.run()
            dockTileConnection?.apply()
            try profileStore.recordProcessID(
                process.processIdentifier,
                for: profileURL
            )
        } catch {
            if process.isRunning {
                process.terminate()
            }
            if removeProfileOnFailure {
                try? profileStore.removeProfile(at: profileURL)
            } else {
                try? profileStore.clearProcessID(for: profileURL)
            }
            throw error
        }

        return LaunchedSession(
            id: id,
            process: process,
            profileURL: profileURL,
            metadata: metadata,
            dockTileConnection: dockTileConnection
        )
    }

    private static func removeProfileWithRetries(
        _ profileURL: URL,
        profileStore: ProfileStore,
        remainingAttempts: Int = 5
    ) {
        do {
            try profileStore.removeProfile(at: profileURL)
        } catch where remainingAttempts > 1 {
            DispatchQueue.global(qos: .utility).asyncAfter(
                deadline: .now() + 1
            ) {
                removeProfileWithRetries(
                    profileURL,
                    profileStore: profileStore,
                    remainingAttempts: remainingAttempts - 1
                )
            }
        } catch {
            // The next app launch exposes leftovers for explicit user cleanup.
        }
    }
}

enum SessionLauncherError: LocalizedError {
    case profileAlreadyRunning
    case profileIsNotPersistent

    var errorDescription: String? {
        switch self {
        case .profileAlreadyRunning:
            "That profile is already running."
        case .profileIsNotPersistent:
            "Only saved profiles can be opened again."
        }
    }
}
